import type { Task } from './types';
const url = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const key = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;
const h = (): Record<string, string> => ({ apikey: key!, 'Content-Type': 'application/json' });
export const sharedEnabled = () => Boolean(url && key && url.startsWith('https://'));
export function configError(): string | null { if (!url && !key) return null; if (!url) return 'VITE_SUPABASE_ANON_KEY is set but VITE_SUPABASE_URL is missing.'; if (!key) return 'VITE_SUPABASE_URL is set but VITE_SUPABASE_ANON_KEY is missing.'; if (!url.startsWith('https://')) return `VITE_SUPABASE_URL must be a URL (https://…), got "${url.slice(0, 40)}…"`; return null; }
async function errMsg(r: Response): Promise<string> { try { const b = await r.json(); return b.message || b.error || b.msg || r.statusText || `HTTP ${r.status}`; } catch { return `HTTP ${r.status} ${r.statusText}`; } }
const from = (r: Record<string, unknown>): Task => ({ id: r.id as string, title: r.title as string, description: r.description as string, assignedTo: r.assigned_to as string, deadline: r.deadline as string, createdAt: r.created_at as string, updatedAt: r.updated_at as string, status: r.status as Task['status'], priority: r.priority as Task['priority'], notes: r.notes as string, completedAt: r.completed_at as string | null, previousStatus: r.previous_status as Task['previousStatus'], movedToBacklogAt: r.moved_to_backlog_at as string | null, submittedForReviewAt: r.submitted_for_review_at as string | null });
const toRow = (t: Task) => ({ id: t.id, title: t.title, description: t.description, assigned_to: t.assignedTo, deadline: t.deadline, created_at: t.createdAt, updated_at: t.updatedAt, status: t.status, priority: t.priority, notes: t.notes, completed_at: t.completedAt, previous_status: t.previousStatus, moved_to_backlog_at: t.movedToBacklogAt, submitted_for_review_at: t.submittedForReviewAt });
export async function checkConnection(): Promise<string | null> { try { const r = await fetch(`${url}/rest/v1/tasks?select=id&limit=0`, { headers: h() }); if (!r.ok) return `Supabase: ${await errMsg(r)}`; return null; } catch (e) { return `Cannot reach Supabase: ${e instanceof Error ? e.message : String(e)}`; } }
export async function loadSharedTasks(): Promise<Task[]> { const r = await fetch(`${url}/rest/v1/tasks?select=*`, { headers: h() }); if (!r.ok) throw new Error(await errMsg(r)); return (await r.json() as Record<string, unknown>[]).map(from); }
export async function saveSharedTask(t: Task): Promise<string | null> { try { const r = await fetch(`${url}/rest/v1/tasks?on_conflict=id`, { method: 'POST', headers: { ...h(), Prefer: 'resolution=merge-duplicates' }, body: JSON.stringify(toRow(t)) }); if (!r.ok) return await errMsg(r); return null; } catch (e) { return e instanceof Error ? e.message : String(e); } }
export async function saveSharedTasks(tasks: Task[]): Promise<string | null> { if (!tasks.length) return null; try { const r = await fetch(`${url}/rest/v1/tasks?on_conflict=id`, { method: 'POST', headers: { ...h(), Prefer: 'resolution=merge-duplicates' }, body: JSON.stringify(tasks.map(toRow)) }); if (!r.ok) return await errMsg(r); return null; } catch (e) { return e instanceof Error ? e.message : String(e); } }
export async function removeSharedTask(id: string): Promise<string | null> { try { const r = await fetch(`${url}/rest/v1/tasks?id=eq.${encodeURIComponent(id)}`, { method: 'DELETE', headers: h() }); if (!r.ok) return await errMsg(r); return null; } catch (e) { return e instanceof Error ? e.message : String(e); } }
